In [7]:
import pandas as pd
import numpy as np
import re
import string
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt

In [2]:
sample = pd.read_csv("sample_submission.csv",encoding = "ISO-8859-1")
sample.head(2)

   id  target
0   0       0
1   2       0

In [3]:
test_limpio = pd.read_csv("test_limpio.csv",encoding = "ISO-8859-1")
test_limpio.head(2)

,id,keyword,location,text,cantidad_links,cantidad_signos_pregunta,repeticiones,longitud_tweet,letras_seguidas,sentimiento,...,patience jonathan,plans to,police post,provoke outrage,read by,rescuers are,insultos_por_tweet,expresiones_por_tweet,kill,died
0,0,NaN,NaN,just happened a terrible car crash,0,0,1,40,2,-1.00,...,0,0,0,0,0,0,0,0,0,0
1,2,NaN,NaN,heard about earthquake is different cities sta...,0,0,1,70,2,0.25,...,0,0,0,0,0,0,0,0,0,0

In [4]:
test_limpio_sin_texto = test_limpio.drop(['text','keyword','location'], axis=1)
test_limpio_sin_texto.head()

,id,cantidad_links,cantidad_signos_pregunta,repeticiones,longitud_tweet,letras_seguidas,sentimiento,objetividad,the,a,...,patience jonathan,plans to,police post,provoke outrage,read by,rescuers are,insultos_por_tweet,expresiones_por_tweet,kill,died
0,0,0,0,1,40,2,-1.00,1.00,0,4,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,1,70,2,0.25,0.55,0,6,...,0,0,0,0,0,0,0,0,0,0
2,3,0,0,1,100,2,0.00,0.00,3,7,...,0,0,0,0,0,0,0,0,0,0
3,9,0,0,1,40,1,0.00,0.00,0,3,...,0,0,0,0,0,0,0,0,0,0
4,11,0,0,1,50,2,0.00,0.00,0,4,...,0,0,0,0,0,0,0,0,0,0

In [5]:
train_limpio = pd.read_csv("train_limpio.csv",encoding = "ISO-8859-1")
train_limpio.head(2)

,text,target,cantidad_links,cantidad_signos_pregunta,repeticiones,longitud_tweet,letras_seguidas,sentimiento,objetividad,the,...,patience jonathan,plans to,police post,provoke outrage,read by,rescuers are,insultos_por_tweet,expresiones_por_tweet,kill,died
0,our deeds are the reason of this earthquake ma...,1,0,0,1,70,2,0.0,0.0,1,...,0,0,0,0,0,0,0,0,0,0
1,forest fire near la ronge sask canada,1,0,0,1,40,1,0.1,0.4,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
df_x=train_limpio.drop(['text', 'target'], axis=1)
df_x.head()

,cantidad_links,cantidad_signos_pregunta,repeticiones,longitud_tweet,letras_seguidas,sentimiento,objetividad,the,a,to,...,patience jonathan,plans to,police post,provoke outrage,read by,rescuers are,insultos_por_tweet,expresiones_por_tweet,kill,died
0,0,0,1,70,2,0.00000,0.0000,1,8,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,40,1,0.10000,0.4000,0,6,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,130,2,-0.01875,0.3875,1,8,1,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,60,1,0.00000,0.0000,0,4,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,1,90,2,0.00000,0.0000,0,5,2,...,0,0,0,0,0,0,0,0,0,0

In [9]:
df_y=train_limpio.target
df_y

0       1
1       1
2       1
3       1
4       1
       ..
7129    1
7130    1
7131    1
7132    1
7133    1
Name: target, Length: 7134, dtype: int64

In [10]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

In [31]:
classifier = KNeighborsClassifier(n_neighbors=10)
classifier.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=10)

In [32]:
y_pred = classifier.predict(x_test)

In [33]:
count = 0
for i in range( len(y_pred)):
    if y_pred[i]==y_train.values[i]:
        count = count+1
print(count)
print(len(y_pred))
print(count/len(y_pred))

770
1427
0.539593552908199

In [37]:
from sklearn.model_selection import KFold
from sklearn.metrics import f1_score

In [40]:
kf = KFold(n_splits = 5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [41]:
train_sin_texto = train_limpio.drop('text',axis=1)

## Evaluo el algoritmo

In [46]:
for train_index,test_index in kf.split(train_sin_texto):
    x_train,x_test = train_sin_texto.drop(['target'], axis=1).loc[train_index], train_sin_texto.drop([ 'target'], axis=1).loc[test_index]
    y_train,y_test = train_sin_texto.target[train_index], train_sin_texto.target[test_index]
    
    classifier = KNeighborsClassifier(n_neighbors=1)
    classifier.fit(x_train, y_train)
    
    #error de entrenamiento:
    pred = classifier.predict(x_train)
    print('Error de entrenamiento: ',f1_score(y_train.values, pred, average='macro'))
    
    
        
    #error de test:
    pred = classifier.predict(x_test)
    print('Error de test: ',f1_score(y_test.values, pred, average='macro'))

Error de entrenamiento:  0.9903409505484049
Error de test:  0.5538542745193576
Error de entrenamiento:  0.9893835217241429
Error de test:  0.5502020771476178
Error de entrenamiento:  0.9908523840543286
Error de test:  0.5410253442318538
Error de entrenamiento:  0.9908294146736233
Error de test:  0.5455976537856464
Error de entrenamiento:  0.9896758839474618
Error de test:  0.5566806407068501

## Bastante malo, obviamente con n_neighbours=1 el train da excelente porque busca el mas parecido a un registro del train en el mismo train asique devuelve el mismo,pero el error de test indica que es bastante malo, pruebo si funciona mejor aumentando la cantidad de vecinos

In [45]:
for train_index,test_index in kf.split(train_sin_texto):
    x_train,x_test = train_sin_texto.drop(['target'], axis=1).loc[train_index], train_sin_texto.drop([ 'target'], axis=1).loc[test_index]
    y_train,y_test = train_sin_texto.target[train_index], train_sin_texto.target[test_index]
    
    classifier = KNeighborsClassifier(n_neighbors=3)
    classifier.fit(x_train, y_train)
    
    #error de entrenamiento:
    pred = classifier.predict(x_train)
    print('Error de entrenamiento: ',f1_score(y_train.values, pred, average='macro'))
    
    
        
    #error de test:
    pred = classifier.predict(x_test)
    print('Error de test: ',f1_score(y_test.values, pred, average='macro'))

Error de entrenamiento:  0.789917545354551
Error de test:  0.5690137000115614
Error de entrenamiento:  0.7869382520600221
Error de test:  0.5679602568538622
Error de entrenamiento:  0.7897687068982718
Error de test:  0.5662914562914563
Error de entrenamiento:  0.7931287495325496
Error de test:  0.5678815844333562
Error de entrenamiento:  0.79273025733936
Error de test:  0.5717538272432674

## No lo hace